### ISSUE TITLE
Implement understanding of segmentation

### ISSUE THREAD

**Issue by angus-lherrou** [clamsproject/app-aapb-pua-kaldi-wrapper#1]
Currently, this CLAMS app only targets AudioDocuments in the documents list and does not look for segmentation information in existing views. This is a planned feature for the future.

**Comment by keighrim** [comment]
This is kind of done at https://github.com/clamsproject/app-puakaldi-segmented-wrapper, but in the future we'd like to merge two codebases with some implementation of *optional* required input types. (see https://github.com/clamsproject/clams-python/issues/29). I'll leave this open until then.

**Comment by keighrim** [comment]
done via #10.
