### ISSUE TITLE
Issues with Apple M1 & port: 5000 with Mac OS

### ISSUE THREAD

**Issue by Brendayy** [clamsproject/app-aapb-pua-kaldi-wrapper#17]
I am using 2021 Mbp with M1 (Apple Silicon). OS is macOS Ventura 13.2.1, some of the errors occur:

## 1. ARM architecture
```bash
The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```
Solution: add `--platform linux/amd64` after `docker run`
```bash
$ docker run --platform linux/amd64 -p 5000:5000 -v /Users/Shared/archive:/data --rm keighrim/app-aapb-pua-kaldi-wrapper:v0.2.3
```
## 2. Port 5000 already in use
```bash
docker: Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:5000 -> 0.0.0.0:0: listen tcp 0.0.0.0:5000: bind: address already in use.
ERRO[0000] error waiting for container: context canceled
```
Reason: according to https://nono.ma/port-5000-used-by-control-center-in-macos-controlce, `Control Center` is using 5000 by default. * *"even if you use brute force (and kill) the application, it will restart itself...The process running on this port turns out to be an AirPlay server. You can deactivate it in System Preferences › Sharing and uncheck AirPlay Receiver to release port 5000".* *
<img width="1076" alt="Screenshot 2023-03-10 at 2 56 06 PM" src="https://user-images.githubusercontent.com/43281544/224429672-e9056afe-0994-425b-8758-bc66542fe826.png">

**Question: should I deactivate AirPlay on my local machine so that I can use 5000?**
For now, my solution is to use another port:**5001**:
```bash
$ docker run --platform linux/amd64 -p 5001:5000 -v /Users/Shared/archive:/data --rm keighrim/app-aapb-pua-kaldi-wrapper:v0.2.3
```
## 3. No matches found with curl
```bash
zsh: no matches found: [https://0.0.0.0:5001?pretty](https://0.0.0.0:5001/?pretty)
```

Solution: put quotes around url, also keep in mind use the **new port** from above:
```bash
$ curl 'https://0.0.0.0:5001?pretty'
$ curl -H "Accept: application/json" -X POST -d@input.mmif -s 'http://0.0.0.0:5001?pretty' > output.mmif
```

**Comment by keighrim** [comment]
This cab be a nice addition to the app user manual. 

@wricketts while you're working on https://github.com/clamsproject/clams-python/issues/161, can you find a proper spot in the `clamsapp.md` for the above report from Yangyang and squeeze the material into the md file?

**Comment by wricketts** [comment]
Done.
